// Generated by ./render-jobs.sh from value.yaml. Do not edit directly.
def sourceRepo = PIPELINE_REPO
def sourceBranch = PIPELINE_BRANCH
def sourceCredentials = PIPELINE_CREDENTIALS
def applicationCredentials = APPLICATION_CREDENTIALS
def githubApiCredentials = binding.hasVariable('GITHUB_API_CREDENTIALS') ? GITHUB_API_CREDENTIALS : 'none'

pipelineJob('pdd/fetch-pr') {
    description('Poll open GitHub PRs for ntut-Tu/cloth_shop_server and queue matching tests.')
    parameters {
        choiceParam('OWNER', ['ntut-Tu'], 'Configured GitHub owner')
        choiceParam('REPOSITORY', ['cloth_shop_server'], 'Configured GitHub repository')
        choiceParam('HEAD_BRANCH', ['range-filtering'], 'PR source branch')
        choiceParam('BASE_BRANCH', ['main'], 'PR target branch')
        choiceParam('TEST_JOB', ['/pdd/test-all-server'], 'Downstream Jenkins test job')
        choiceParam('POLL', ['H/30 * * * *'], 'Jenkins cron schedule')
        choiceParam('MAX_EMPTY_POLLS', ['5'], 'Stop automatic polling after this many consecutive polls without a matching PR')
        booleanParam('RESET_POLLING', false, 'Reset the empty poll counter and resume automatic polling')
        booleanParam('FORCE_RETEST', false, 'Queue tests again for matching PRs even if their revision was already dispatched')
        choiceParam('GITHUB_API_CREDENTIALS', [githubApiCredentials], 'Managed by Jenkins config: github-api or none')
        choiceParam('APPLICATION_GIT_CREDENTIALS', [applicationCredentials], 'Managed by Jenkins config: none or application-git')
    }
    triggers {
        cron('H/30 * * * *')
    }
    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url(sourceRepo)
                        if (sourceCredentials) { credentials(sourceCredentials) }
                    }
                    branch(sourceBranch)
                }
            }
            scriptPath('pipelines/github-pr-poll.Jenkinsfile')
            lightweight(false)
        }
    }
}
