"""Render fetch PR Job DSL from a small, validated YAML file."""
import argparse
import os
from pathlib import Path
import re
import sys
import tempfile

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VALUES = ROOT / 'value.yaml'
DEFAULT_OUTPUT = ROOT / 'jobs' / 'generated_fetch_pr.groovy'
NAME = re.compile(r'[A-Za-z0-9][A-Za-z0-9_.-]*\Z')
BRANCH = re.compile(r'[A-Za-z0-9_][A-Za-z0-9_./-]*\Z')
REPOSITORY = re.compile(r'([A-Za-z0-9][A-Za-z0-9_.-]*)/([A-Za-z0-9][A-Za-z0-9_.-]*)\Z')
JOB_PATH = re.compile(r'/[A-Za-z0-9][A-Za-z0-9_.-]*(?:/[A-Za-z0-9][A-Za-z0-9_.-]*)+\Z')
POLL = re.compile(r'[A-Za-z0-9H*/ ,\-]+\Z')
REQUIRED = {'name', 'repository', 'head_branch', 'test_job'}
OPTIONAL = {'base_branch', 'poll', 'max_empty_polls'}
RESERVED_NAMES = {'integration-test', 'cloth-shop-api-test', 'test-all-server'}


class UniqueKeyLoader(yaml.SafeLoader):
    pass


def unique_mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if not isinstance(key, str):
            raise ValueError('YAML mapping keys must be strings')
        if key in result:
            raise ValueError(f'duplicate YAML key: {key}')
        result[key] = loader.construct_object(value_node)
    return result


UniqueKeyLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def groovy(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def load_jobs(path):
    values = yaml.load(path.read_text(), Loader=UniqueKeyLoader)
    if not isinstance(values, dict) or set(values) != {'fetch_pr_jobs'}:
        raise ValueError('value.yaml must contain only fetch_pr_jobs')
    jobs = values['fetch_pr_jobs']
    if not isinstance(jobs, list) or not jobs:
        raise ValueError('fetch_pr_jobs must be a nonempty list')
    seen = set()
    for index, job in enumerate(jobs, 1):
        label = f'fetch_pr_jobs[{index}]'
        if not isinstance(job, dict) or not REQUIRED <= set(job) or not set(job) <= REQUIRED | OPTIONAL:
            raise ValueError(f'{label} requires {", ".join(sorted(REQUIRED))}; optional: {", ".join(sorted(OPTIONAL))}')
        job.setdefault('base_branch', 'main')
        job.setdefault('poll', 'H/30 * * * *')
        job.setdefault('max_empty_polls', 5)
        for key in REQUIRED:
            if not isinstance(job[key], str) or not job[key]:
                raise ValueError(f'{label}.{key} must be a nonempty string')
        if not NAME.fullmatch(job['name']) or job['name'] in seen or job['name'] in RESERVED_NAMES:
            raise ValueError(f'{label}.name is invalid or duplicated')
        seen.add(job['name'])
        if not REPOSITORY.fullmatch(job['repository']):
            raise ValueError(f'{label}.repository must be owner/repo')
        for key in ('head_branch', 'base_branch'):
            branch = job[key]
            if not BRANCH.fullmatch(branch) or '..' in branch or branch.endswith('/'):
                raise ValueError(f'{label}.{key} is invalid')
        if not JOB_PATH.fullmatch(job['test_job']):
            raise ValueError(f'{label}.test_job must be an absolute Jenkins job path')
        if not POLL.fullmatch(job['poll']) or len(job['poll'].split()) != 5:
            raise ValueError(f'{label}.poll must be a five-field Jenkins cron expression')
        if type(job['max_empty_polls']) is not int or not 1 <= job['max_empty_polls'] <= 1000:
            raise ValueError(f'{label}.max_empty_polls must be an integer from 1 to 1000')
    return jobs


def render(jobs):
    lines = [
        '// Generated by ./render-jobs.sh from value.yaml. Do not edit directly.',
        'def sourceRepo = PIPELINE_REPO',
        'def sourceBranch = PIPELINE_BRANCH',
        'def sourceCredentials = PIPELINE_CREDENTIALS',
        'def applicationCredentials = APPLICATION_CREDENTIALS',
        'def githubApiCredentials = GITHUB_API_CREDENTIALS',
        '',
    ]
    for job in jobs:
        owner, repository = job['repository'].split('/')
        lines.extend([
            f"pipelineJob({groovy('pdd/' + job['name'])}) {{",
            f"    description({groovy('Poll open GitHub PRs for ' + job['repository'] + ' and queue matching tests.')})",
            '    parameters {',
            f"        choiceParam('OWNER', [{groovy(owner)}], 'Configured GitHub owner')",
            f"        choiceParam('REPOSITORY', [{groovy(repository)}], 'Configured GitHub repository')",
            f"        choiceParam('HEAD_BRANCH', [{groovy(job['head_branch'])}], 'PR source branch')",
            f"        choiceParam('BASE_BRANCH', [{groovy(job['base_branch'])}], 'PR target branch')",
            f"        choiceParam('TEST_JOB', [{groovy(job['test_job'])}], 'Downstream Jenkins test job')",
            f"        choiceParam('POLL', [{groovy(job['poll'])}], 'Jenkins cron schedule')",
            f"        choiceParam('MAX_EMPTY_POLLS', [{groovy(str(job['max_empty_polls']))}], 'Stop automatic polling after this many consecutive polls without a matching PR')",
            "        booleanParam('RESET_POLLING', false, 'Reset the empty poll counter and resume automatic polling')",
            "        choiceParam('GITHUB_API_CREDENTIALS', [githubApiCredentials], 'Managed by Jenkins config: github-api or none')",
            "        choiceParam('APPLICATION_GIT_CREDENTIALS', [applicationCredentials], 'Managed by Jenkins config: none or application-git')",
            '    }',
            '    triggers {',
            f"        cron({groovy(job['poll'])})",
            '    }',
            '    definition {',
            '        cpsScm {',
            '            scm {',
            '                git {',
            '                    remote {',
            '                        url(sourceRepo)',
            '                        if (sourceCredentials) { credentials(sourceCredentials) }',
            '                    }',
            '                    branch(sourceBranch)',
            '                }',
            '            }',
            "            scriptPath('pipelines/github-pr-poll.Jenkinsfile')",
            '            lightweight(false)',
            '        }',
            '    }',
            '}',
            '',
        ])
    return '\n'.join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--values', type=Path, default=DEFAULT_VALUES)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--check', action='store_true', help='Fail if rendered output differs')
    arguments = parser.parse_args(argv)
    try:
        jobs = load_jobs(arguments.values)
        content = render(jobs)
    except (OSError, yaml.YAMLError, ValueError) as error:
        parser.error(str(error))
    if arguments.check:
        if not arguments.output.exists() or arguments.output.read_text() != content:
            print(f'Outdated generated Job DSL: {arguments.output}', file=sys.stderr)
            return 1
        print(f'Up to date: {arguments.output}')
    else:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary = tempfile.mkstemp(prefix='.fetch-pr-', dir=arguments.output.parent)
        try:
            with os.fdopen(descriptor, 'w') as stream:
                stream.write(content)
            os.chmod(temporary, 0o644)
            os.replace(temporary, arguments.output)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
        print(f'Rendered {len(jobs)} fetch PR job(s): {arguments.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
